class AccountsConstants:
    ACCOUNTS_PAGE_TITLE_XPATH = "//span[@class='entity-title left'][text()='Accounts ']"
    NEW_BUTTON_XPATH = "//button[text()='New']"

    WIZARD_ID_INPUT_XPATH = "//input[@id='accountID']"
    WIZARD_EXT_ID_CLIENT_INPUT_XPATH = "//input[@id='clientAccountID']"
    WIZARD_CLIENT_COMBOBOX_XPATH = "//input[@id='accountGroup']"
    WIZARD_DESCRIPTION_INPUT_XPATH = "//input[@id='accountDesc']"
    WIZARD_POSITION_SOURCE_COMBOBOX_XPATH = "//input[@id='positionSource']"
    WIZARD_CLEARING_ACCOUNT_TYPE_COMBOBOX_XPATH = "//input[@id='clearingAccountType']"
    WIZARD_CLIENT_ID_SOURCE_COMBOBOX_XPATH = "//input[@id='clientAccountIDSource']"
    WIZARD_DEFAULT_ACCOUNT_CHECKBOX_XPATH = "//nb-checkbox[@formcontrolname='defaultAccount']"
    WIZARD_TRADE_CONFIRM_ELIGIBILITY_CHECKBOX_XPATH = "//nb-checkbox[@formcontrolname='tradeConfirmEligibility']"
    WIZARD_CLIENT_MATCHING_ID_INPUT_XPATH = "//input[@formcontrolname='clientMatchingID']"
    WIZARD_BO_FILED_1_INPUT_XPATH = "//input[@id='confirmationMisc0']"
    WIZARD_BO_FILED_2_INPUT_XPATH = "//input[@id='confirmationMisc1']"
    WIZARD_BO_FILED_3_INPUT_XPATH = "//input[@id='confirmationMisc2']"
    WIZARD_BO_FILED_4_INPUT_XPATH = "//input[@id='confirmationMisc3']"
    WIZARD_BO_FILED_5_INPUT_XPATH = "//input[@id='confirmationMisc4']"
    WIZARD_COMMISSION_EXEMPTION_CHECKBOX_XPATH = "//nb-checkbox[@formcontrolname='brokerCommissionExemption']"
    WIZARD_COUNTERPART_COMBOBOX_XPATH = "//input[@id='counterpart']"
    WIZARD_DEFAULT_ROUTE_COMBOBOX_XPATH = "//input[@id='defaultRoute']"
    WIZARD_SAVE_BUTTON_XPATH = "//button[text()='Save Changes']"

    ADD_DIMENSIONS_ENTITY_BUTTON_XPATH = "//nb-accordion-item[2]/nb-accordion-item-body/div/div/ng2-smart-table/table/thead/tr[2]/th[1]/a"
    ADD_ROUTES_ENTITY_BUTTON_XPATH = "//nb-accordion-item[3]/nb-accordion-item-body/div/div/ng2-smart-table/table/thead/tr[2]/th[1]/a"

    DIMENSIONS_VENUE_ACCOUNT_FILTER_XPATH = "//nb-accordion/nb-accordion-item[2]//th[contains(@class, 'venueAccountName')]//input"
    DIMENSIONS_VENUE_FILTER_XPATH = "//nb-accordion/nb-accordion-item[2]//th[contains(@class, ' venue ')]//input"
    DIMENSIONS_ACCOUNT_ID_SOURCE_FILTER_XPATH = "//nb-accordion/nb-accordion-item[2]//th[contains(@class, 'venueAccountIDSource')]//input"
    DIMENSIONS_DEFAULT_ROUTE_FILTER_XPATH = "//nb-accordion/nb-accordion-item[2]//th[contains(@class, 'defaultRoute')]//input"
    DIMENSIONS_STAMP_EXEMPT_FILTER_XPATH = "//nb-accordion/nb-accordion-item[2]//th[contains(@class, 'stampFeeExemption')]//input"
    DIMENSIONS_LEVY_EXEMPT_FILTER_XPATH = "//nb-accordion/nb-accordion-item[2]//th[contains(@class, 'levyFeeExemption')]//input"
    DIMENSIONS_PER_TRANSAC_EXEMPT_FILTER_XPATH = "//nb-accordion/nb-accordion-item[2]//th[contains(@class, 'perTransacFeeExemption')]//input"
    DIMENSIONS_VENUE_CLIENT_ACCOUNT_NAME_FILTER_XPATH = "//nb-accordion/nb-accordion-item[2]//th[contains(@class, 'venueClientAccountName')]//input"

    DIMENSIONS_EDIT_BUTTON_XPATH = "//nb-accordion/nb-accordion-item[2]//a[contains(@class, 'edit')]"
    DIMENSIONS_DELETE_BUTTON_XPATH = "//nb-accordion/nb-accordion-item[2]//a[contains(@class, 'delete')]"
    DIMENSIONS_CREATE_ENTITY_BUTTON_XPATH = "//nb-accordion/nb-accordion-item[2]//a[contains(@class, 'create')]"
    DIMENSIONS_DISCARD_ENTITY_BUTTON_XPATH = "//nb-accordion/nb-accordion-item[2]//a[contains(@class, 'cancel')]"

    DIMENSIONS_VENUE_ACCOUNT_INPUT_XPATH = "//nb-accordion/nb-accordion-item[2]//input[@placeholder='Venue Account *']"
    DIMENSIONS_VENUE_COMBOBOX_XPATH = "//nb-accordion/nb-accordion-item[2]//input[@placeholder='Venue *']"
    DIMENSIONS_ACCOUNT_ID_SOURCE_COMBOBOX_XPATH = "//nb-accordion/nb-accordion-item[2]//input[@placeholder='Account ID Source *']"
    DIMENSIONS_DEFAULT_ROUTE_COMBOBOX_XPATH = "//nb-accordion/nb-accordion-item[2]//input[@placeholder='Default Route']"
    DIMENSIONS_STAMP_EXEMPT_CHECKBOX_XPATH = "//nb-accordion/nb-accordion-item[2]//td[6]//nb-checkbox"
    DIMENSIONS_LEVY_EXEMPT_CHECKBOX_XPATH = "//nb-accordion/nb-accordion-item[2]//td[7]//nb-checkbox"
    DIMENSIONS_PER_TRANSAC_EXEMPT_CHECKBOX_XPATH = "//nb-accordion/nb-accordion-item[2]//td[8]//nb-checkbox"
    DIMENSIONS_VENUE_CLIENT_ACCOUNT_NAME_INPUT_XPATH = "//nb-accordion/nb-accordion-item[2]//input[@placeholder='Venue Client Account Name']"

    ROUTES_ROUTE_ACCOUNT_NAME_FILTER_XPATH = "//nb-accordion/nb-accordion-item[3]//th[contains(@class, 'routeSecActName')]//input"
    ROUTES_ROUTE_FILTER_XPATH = "//nb-accordion/nb-accordion-item[3]//th[contains(@class, ' route ')]//input"
    ROUTES_ROUTE_ACCOUNT_NAME_INPUT_XPATH = "//nb-accordion/nb-accordion-item[3]//input[@placeholder='Route Account Name *']"
    ROUTES_ROUTE_COMBOBOX_XPATH = "//nb-accordion/nb-accordion-item[3]//input[@placeholder='Route *']"

    ROUTES_EDIT_BUTTON_XPATH = "//nb-accordion/nb-accordion-item[3]//a[contains(@class, 'edit')]"
    ROUTES_DELETE_BUTTON_XPATH = "//nb-accordion/nb-accordion-item[3]//a[contains(@class, 'delete')]"
    ROUTES_CREATE_ENTITY_BUTTON_XPATH = "//nb-accordion/nb-accordion-item[3]//a[contains(@class, 'create')]"
    ROUTES_DISCARD_ENTITY_BUTTON_XPATH = "//nb-accordion/nb-accordion-item[3]//a[contains(@class, 'cancel')]"

    ID_INPUT_GRID_FILTER_XPATH = "//ag-grid-angular/div/div[1]/div/div[1]/div[2]/div/div[2]/div[1]/div[1]/div/input"
    ID_VALUE_GRID_XPATH = "//div[contains(@class, 'ag-row-first')]//div[@col-id='accountID']//span[contains(@class, 'ag-group-value')]"
    MORE_ACTIONS_BUTTON_GRID_XPATH = "//nb-icon[@title='More Actions']"
    EDIT_ENTITY_BUTTON_GRID_XPATH = "//nb-icon[@nbtooltip='Edit']"
    CLONE_ENTITY_BUTTON_GRID_XPATH = "//nb-icon[@nbtooltip='Clone']"
    DOWNLOAD_PDF_ENTITY_BUTTON_GRID_XPATH = "//nb-icon[@nbtooltip='Download PDF']"
    ENABLE_DISABLE_TOGGLE_BUTTON_GRID_XPATH = "//div[contains(@class, 'toggle')]"

    CONFIRM_ACTION_BUTTON_XPATH = "//div[@class='confirmation-dialog']//button[text()='Ok']"

    POPUP_TEXT_XPATH = "//nb-toast//span[@class='title subtitle']"
