class Constants:
    class MainPage:
        PAGE_TITLE = '//*[@class="entity-title left"][normalize-space()="User Lists"]'
        GLOBAL_FILTER = '//nb-card-header//div//input[@placeholder="Filter"]'
        HELP_ICON_BUTTON = '//nb-card-header//*[@nbtooltip="Help"]//a'
        DOWNLOAD_CSV_BUTTON = '//nb-card-header//*[@nbtooltip="Download CSV"]//a'
        FULL_SCREEN_BUTTON = '//nb-card-header//*[contains(@nbtooltip, "Full Screen")]//a'
        REFRESH_PAGE_BUTTON = '//nb-card-header//*[@nbtooltip="Refresh Page"]//a'
        NEW_BUTTON = '//nb-card-header//button[normalize-space()="New"]'

        NAME_FILTER = '//nb-card-body//*[@style="width: 200px; left: 0px;"]//input[@class="ag-floating-filter-input"]'
        DESCRIPTION_FILTER = '//nb-card-body//*[@style="width: 200px; left: 200px;"]//input[@class="ag-floating-filter-input"]'
        MORE_ACTION_BUTTON = '//*[@data-name="more-vertical"]'
        EDIT_BUTTON = '//*[@class="cdk-overlay-pane"]//*[@data-name="edit"]'
        CLONE_BUTTON = '//*[@class="cdk-overlay-pane"]//*[@data-name="copy"]'
        DELETE_BUTTON = '//*[@class="cdk-overlay-pane"]//*[@data-name="trash-2"]'
        DOWNLOAD_PDF_BUTTON = '//*[@class="cdk-overlay-pane"]//*[@data-name="download"]'
        PIN_BUTTON = '//*[@class="cdk-overlay-pane"]//*[@icon="pinned-outline" or @icon="unpinned-outline"]'
        SEARCHED_USER_LIST = '//*[normalize-space()="{}"]'

    class Wizard:
        HEADER_LINK = '//nb-card-header//div/a'
        USER_LIST_DATA_IN_HEADER_TEXT = '//nb-card-header//div[@class="breadcrumbs-div"]'
        HELP_ICON_BUTTON = '//nb-card-header//*[@nbtooltip="Help"]//a'
        DOWNLOAD_PDF_FILE_BUTTON = '//nb-card-header//*[@data-name="download"]'
        CLOSE_WIZARD_BUTTON = '//nb-card-header//*[@data-name="close"]'
        CLEAR_CHANGES_BUTTON = '//button[normalize-space()="Clear Changes"]'
        SAVE_CHANGES_BUTTON = '//button[normalize-space()="Save Changes"]'
        REVERT_CHANGES_BUTTON = '//button[normalize-space()="Revert Changes"]'
        CANCEL_BUTTON = '//button[normalize-space()="Cancel"]'
        OK_BUTTON = '//button[normalize-space()="OK"]'
        NO_BUTTON = '//button[normalize-space()="No"]'
        FOOTER_ERROR_TEXT = '//nb-card-footer//nb-alert//span'

    class ValuesTab:
        USER_LIST_NAME = '//input[@formcontrolname="userListName"]'
        USER_LIST_DESCRIPTION = '//input[@formcontrolname="userListDescription"]'
        PLUS_BUTTON = '//button[@nbtooltip="Add"]'
        SAVE_CHECKMARK_BUTTON = '//p-table//*[@data-name="checkmark"]'
        CANCEL_BUTTON = '//p-table//*[@data-name="close"]'
        EDIT_BUTTON = '//p-table//*[@data-name="edit"]'
        DELETE_BUTTON = '//p-table//*[@data-name="trash-2"]'
        USER = '//p-table//*[@id="user"]'
        USER_FILTER = '//p-table//input[@placeholder="Filter"]'
