class RootConstants:
    HEADER_CONTAINER_CSS_SELECTOR = "div[class='header-container']"

    SIDE_MENU_TOGGLE_CSS_LOCATOR = "a[class='sidebar-toggle']"

    GENERAL_TOGGLE_CSS_SELECTOR = "a[title='General']"
    SETTINGS_ITEM_XPATH = "//span[text()='Settings']"
    MDENTITLEMENTS_ITEM_XPATH = "//span[text()='MDEntitlements']"
    ADMIN_COMMAND_ITEM_XPATH = "//span[text()='AdminCommand']"

    USERS_TOGGLE_CSS_SELECTOR = "a[title='Users']"
    USERS_ITEM_XPATH = "//*[@href='#/pages/users/view']//span[text()='Users']"
    USER_SESSIONS_ITEM_XPATH = "//span[text()='User Sessions']"
    DESKS_ITEM_XPATH = "//span[text()='Desks']"

    REFERENCE_DATA_TOGGLE_CSS_SELECTOR = "a[title='Reference Data']"
    VENUES_ITEM_XPATH = "//span[text()='Venues']"
    SUBVENUES_ITEM_XPATH = "//span[text()='SubVenues']"
    LISTING_GROUPS_ITEM_XPATH = "//span[text()='ListingGroups']"
    LISTINGS_ITEM_XPATH = "//span[text()='Listings']"
    RECOVER_HISTORICAL_VOLUME_ITEM_XPATH = "//span[text()='Recover Historical Volume']"
    INSTR_SYMBOL_INFO_ITEM_XPATH = "//span[text()='InstrSymbolInfo']"
    INSTRUMENT_GROUP_ITEM_XPATH = "//span[text()='Instrument Group']"
    INSTRUMENT_LIST_ITEM_XPATH = "//span[text()='Instrument List']"

    CLIENT_ACCOUNTS_TOGGLE_CSS_SELECTOR = "a[title='Client/Accounts']"
    ACCOUNTS_ITEM_XPATH = "//span[text()='Accounts']"
    WASHBOOK_ITEM_XPATH = "//span[text()='Wash Books']"
    WASHBOOK_RULES_ITEM_XPATH = "//span[text()='Wash Book Rules']"
    CLIENTS_ITEM_XPATH = "//span[text()='Clients']"
    CLIENT_GROUPS_ITEM_XPATH = "//span[text()='ClientGroups']"
    CLIENT_LIST_ITEM_XPATH = "//span[text()='Client List']"
    CASH_ACCOUNTS_ITEM_XPATH = "//span[text()='CashAccounts']"
    CLIENT_CLIENT_GROUPS_ITEM_XPATH = "//span[text()='ClientClientGroups']"

    ORDER_MANAGEMENT_TOGGLE_CSS_SELECTOR = "a[title='Order Management']"
    EXECUTION_STRATEGIES_ITEM_XPATH = "//span[text()='Execution Strategies']"
    ORDER_MANAGEMENT_RULES_ITEM_XPATH = "//span[text()='Order Management Rules']"

    MIDDLE_OFFICE_TOGGLE_CSS_SELECTOR = "a[title='Middle Office']"
    FEES_ITEM_XPATH = "//span[text()='Fees']"
    COMMISSIONS_ITEM_XPATH = "//span[text()='Commissions']"
    SETTLEMENT_MODEL_ITEM_XPATH = "//span[text()='Settlement Model']"
    FIX_MATCHING_PROFILE_ITEM_XPATH = "//span[text()='FIX Matching Profile']"

    FX_MARKET_MAKING_TOGGLE_CSS_SELECTOR = "a[title='FX Market Making']"
    QUOTING_SESSIONS_ITEM_XPATH = "//span[text()='Quoting Sessions']"
    CLIENT_TIER_ITEM_XPATH = "//span[text()='Client Tier']"
    AUTO_HEDGER_ITEM_XPATH = "//span[text()='Auto Hedger']"

    PRICE_CLEANSING_TOGGLE_CSS_SELECTOR = "a[title='Price Cleansing']"
    CROSSED_VENUE_RATES_ITEM_XPATH = "//span[text()='Crossed Venue Rates']"
    STALE_RATES_ITEM_XPATH = "//span[text()='Stale Rates']"
    RATES_FOLLOWING_TRADES_ITEM_XPATH = "//span[text()='Rates Following Trades']"
    UNBALANCED_RATES_ITEM_XPATH = "//span[text()='Unbalanced Rates']"

    RISK_LIMITS_TOGGLE_CSS_SELECTOR = "a[title='Risk Limits']"
    TRADING_LIMITS_ITEM_XPATH = "//span[text()='TradingLimits']"
    CUM_TRADING_LIMITS_ITEM_XPATH = "//span[text()='CumTradingLimits']"
    LISTING_CUMTRDLMT_COUNTER_ITEM_XPATH = "//span[text()='Listing CumTrdLmt Counter']"
    CUMTRDLMT_COUNTER_ITEM_XPATH = "//span[text()='CumTrdLmt Counter']"
    POSITION_LIMITS_ITEM_XPATH = "//span[text()='PositionLimits']"
    FX_POSITION_LIMITS_ITEM_XPATH = "//span[text()='FX Position Limits']"
    PRICE_TOLERANCE_CONTROL_ITEM_XPATH = "//span[text()='Price Tolerance Control']"
    EXTERNAL_CHECK_ITEM_XPATH = "//span[text()='External Check']"

    POSITIONS_TOGGLE_CSS_SELECTOR = "a[title='Positions']"
    SECURITY_POSITIONS_ITEM_XPATH = "//span[text()='Security Positions']"
    FX_POSITIONS_ITEM_XPATH = "//span[text()='FX Positions']"

    OTHERS_TOGGLE_CSS_SELECTOR = "a[title='Others']"
    COUNTERPARTS_ITEM_XPATH = "//span[text()='Counterparts']"
    INSTITUTIONS_ITEM_XPATH = "//span[text()='Institutions']"
    MARKET_DATA_SOURCE_ITEM_XPATH = "//span[text()='Market Data Source']"
    ROUTES_ITEM_XPATH = "//span[text()='Routes']"
    USER_INSTR_SYMB_BLACK_OUT_ITEM_XPATH = "//span[text()='User Instr Symb Black Out']"
