PROFILE_BUTTON_XPATH = '//*[@class="toggleprofile-content igx-toggle"]/div[1]'
HIDE_HEADER_BUTTON_XPATH = '//*[@class="toggleprofile-content igx-toggle"]/div[2]'
DARK_THEME_BUTTON_XPATH = '//*[@class="toggleprofile-content igx-toggle"]/div[3]'
CONTACT_US_BUTTON_XPATH = '//*[@class="toggleprofile-content igx-toggle"]/div[4]'
LOGOUT_BUTTON_XPATH = '//*[@class="toggleprofile-content igx-toggle"]/div[5]'