class RootConstants:
    HEADER_CONTAINER_CSS_SELECTOR = "div[class='header-container']"

    SIDE_MENU_TOGGLE_CSS_LOCATOR = "a[class='sidebar-toggle']"

    GENERAL_TOGGLE_CSS_SELECTOR = "a[title='General']"
    SETTINGS_ITEM_XPATH = "//span[text()='Settings']"
    ENTITLEMENTS_ITEM_XPATH = "//span[text()='Entitlements']"
    SYSTEM_COMMANDS_ITEM_XPATH = "//span[text()='System Commands']"

    SITE_TOGGLE_CSS_SELECTOR = "a[title='Site']"
    SITE_TAB_XPATH = '//*[@title="Site"]'
    SITE_COLLAPSE_XPATH = '//*[@title="Site"]//..//ul'
    INSTITUTIONS_ITEM_XPATH = "//span[text()='Institutions']"
    ZONES_ITEM_XPATH = "//span[text()='Zones']"
    LOCATIONS_ITEM_XPATH = "//span[text()='Locations']"
    DESKS_ITEM_XPATH = "//span[text()='Desks']"

    USERS_TOGGLE_CSS_SELECTOR = "a[title='Users']"
    USERS_ITEM_XPATH = "//*[@href='#/pages/users/view']//span[text()='Users']"
    USER_SESSIONS_ITEM_XPATH = "//span[text()='User Sessions']"

    REFERENCE_DATA_TOGGLE_CSS_SELECTOR = "a[title='Markets']"
    VENUES_ITEM_XPATH = "//span[text()='Venues']"
    SUBVENUES_ITEM_XPATH = "//span[text()='Sub-Venues']"
    LISTING_GROUPS_ITEM_XPATH = "//span[text()='Listing Groups']"
    LISTINGS_ITEM_XPATH = "//span[text()='Listings']"
    RECOVER_HISTORICAL_VOLUME_ITEM_XPATH = "//span[text()='Recover Historical Volume']"
    INSTR_SYMBOL_INFO_ITEM_XPATH = "//span[text()='Instrument Symbols']"
    INSTRUMENT_GROUPS_ITEM_XPATH = "//span[text()='Instrument Groups']"
    INSTRUMENT_LIST_ITEM_XPATH = "//span[text()='Instrument Lists']"
    VENUE_LISTS_XPATH = "//span[text()='Venue Lists']"

    CLIENT_ACCOUNTS_TOGGLE_CSS_SELECTOR = "a[title='Clients/Accounts']"
    ACCOUNTS_ITEM_XPATH = "//span[text()='Accounts']"
    WASHBOOK_ITEM_XPATH = "//span[text()='Wash Books']"
    WASHBOOK_RULES_ITEM_XPATH = "//span[text()='Wash Book Rules']"
    CLIENTS_ITEM_XPATH = "//span[text()='Clients']"
    CLIENT_GROUPS_ITEM_XPATH = "//span[text()='Client Groups']"
    CLIENT_LIST_ITEM_XPATH = "//span[text()='Client Lists']"
    CASH_ACCOUNTS_ITEM_XPATH = "//span[text()='CashAccounts']"
    CLIENT_CLIENT_GROUPS_ITEM_XPATH = "//span[text()='ClientClientGroups']"

    ORDER_MANAGEMENT_TOGGLE_CSS_SELECTOR = "a[title='Order Management']"
    EXECUTION_STRATEGIES_ITEM_XPATH = "//span[text()='Execution Strategies']"
    ORDER_MANAGEMENT_RULES_ITEM_XPATH = "//span[text()='Order Management Rules']"

    MIDDLE_OFFICE_TOGGLE_CSS_SELECTOR = "a[title='Middle Office']"
    FEES_ITEM_XPATH = "//span[text()='Fees']"
    COMMISSIONS_ITEM_XPATH = "//span[text()='Commissions']"
    SETTLEMENT_MODEL_ITEM_XPATH = "//span[text()='Settlement Models']"
    ALLOCATION_MATCHING_PROFILE_ITEM_XPATH = "//span[text()='Allocation Matching Profiles']"

    FX_MARKET_MAKING_TOGGLE_CSS_SELECTOR = "a[title='Market Making']"
    QUOTING_SESSIONS_ITEM_XPATH = "//span[text()='Quoting Sessions']"
    CLIENT_TIER_ITEM_XPATH = "//span[text()='Client Tiers']"
    AUTO_HEDGER_ITEM_XPATH = "//span[text()='Auto Hedgers']"

    PRICE_CLEANSING_TOGGLE_CSS_SELECTOR = "a[title='Price Cleansing']"
    CROSSED_VENUE_RATES_ITEM_XPATH = "//span[text()='Crossed Venue Rates']"
    STALE_RATES_ITEM_XPATH = "//span[text()='Stale Rates']"
    RATES_FOLLOWING_TRADES_ITEM_XPATH = "//span[text()='Rates Following Trades']"
    UNBALANCED_RATES_ITEM_XPATH = "//span[text()='Unbalanced Rates']"

    RISK_LIMITS_TOGGLE_CSS_SELECTOR = "a[title='Risk Limits']"
    TRADING_LIMITS_ITEM_XPATH = "//span[text()='Trading Limits']"
    BUYING_POWER_ITEM_XPATH = "//span[text()='Buying Power']"
    CUM_TRADING_LIMITS_ITEM_XPATH = "//span[text()='Cum Trading Limits']"
    LISTING_CUMTRDLMT_COUNTER_ITEM_XPATH = "//span[text()='Listing CumTrdLmt Counter']"
    CUMTRDLMT_COUNTER_ITEM_XPATH = "//span[text()='Cum Trading Limit Counters']"
    POSITION_LIMITS_ITEM_XPATH = "//span[text()='Position Limits']"
    RISK_LIMIT_DIMENSIONS_XPATH = "//span[text()='Risk Limit Dimensions']"
    FX_POSITION_LIMITS_ITEM_XPATH = "//span[text()='FX Position Limits']"
    PRICE_TOLERANCE_CONTROL_ITEM_XPATH = "//span[text()='Order Tolerance Limits']"
    EXTERNAL_CHECK_ITEM_XPATH = "//span[text()='External Checks']"
    ORDER_VELOCITY_LIMIT_ITEM_XPATH = "//span[text()='Order Tolerance Limits']"

    POSITIONS_TOGGLE_CSS_SELECTOR = "a[title='Positions']"
    SECURITY_POSITIONS_ITEM_XPATH = "//span[text()='Security Positions']"
    FX_POSITIONS_ITEM_XPATH = "//span[text()='FX Positions']"
    CASH_POSITIONS_XPATH = "//span[text()='Cash Positions']"

    OTHERS_TOGGLE_CSS_SELECTOR = "a[title='Others']"
    COUNTERPARTS_ITEM_XPATH = "//span[text()='Counterparts']"
    INSTITUTIONS_ITEM_XPATH = "//span[text()='Institutions']"
    MARKET_DATA_SOURCE_ITEM_XPATH = "//span[text()='Market Data Sources']"
    ROUTES_ITEM_XPATH = "//span[text()='Routes']"
    USER_INSTR_SYMB_BLACK_OUT_ITEM_XPATH = "//span[text()='User Instr Symb Black Out']"
