SEARCH_SYMBOL_FIELD_XPATH = '//*[@name="txtSearch1"]'
ACCOUNTS_FIELD_XPATH = '//*[text()="Accounts"]/following-sibling::igx-select/descendant ::input'
MODE_BUY_BUTTON_XPATH = '//*[@class="inside-button"]/span[@class="make-bold"]'
MODE_SELL_BUTTON_XPATH = '//*[@class="inside-button-sell"]/span[@class="make-bold"]'
QUANTITY_FIELD_XPATH = '//*[@name="quantity"]'
PRICE_FIELD_XPATH = '//*[@name="price1"]'
ORDER_TYPE_FIELD_XPATH = '//*[@id="select"]/descendant::input'
LIMIT_BUTTON_XPATH = '//*[@id="igx-drop-down-item-270"]'
MARKET_BUTTON_XPATH = '//*[@id="igx-drop-down-item-271"]'
TIME_IN_FORCE_FIELD_XPATH = '//*[@id="select-good"]/descendant::input'
DAY_BUTTON_XPATH = '//*[@id="igx-drop-down-item-279"]'
GOOD_TILL_CANCEL_BUTTON_XPATH = '//*[@id="igx-drop-down-item-280"]'
EXPIRE_DATE_FIELD_XPATH = '//*[@id="igx-date-picker-6"]/descendant::input'
BUY_BUTTON_XPATH = '//*[@class="buttons"]/button'
SELL_BUTTON_XPATH = '//*[@class="buttons"]/button'
CLOSE_BUTTON_XPATH = '//*[@id="order"]/igx-icon'