class OrderTicketConstants:
    SEARCH_SYMBOL_FIELD_XPATH = '//*[@name="txtSearch1"]'
    LIST_OF_SYMBOL_XPATH = '//*[@class="igx-overlay__content"]//span[text()="{}"]'
    ACCOUNTS_FIELD_XPATH = '//*[text()="Accounts"]/following-sibling::igx-select/descendant ::input'
    MODE_BUY_BUTTON_XPATH = '//*[@class="inside-button"]/span[@class="make-bold"]'
    MODE_SELL_BUTTON_XPATH = '//*[@class="inside-button-sell"]/span[@class="make-bold"]'
    QUANTITY_FIELD_XPATH = '//*[@name="quantity"]'
    PRICE_FIELD_XPATH = '//*[@name="price"]'
    ORDER_TYPE_FIELD_XPATH = '//*[@id="select"]/descendant::input'
    LIST_OF_ORDER_TYPE_XPATH = '//*[@class="igx-overlay__content"]//span[text()="{}"]'
    TIME_IN_FORCE_FIELD_XPATH = '//*[@id="select-good"]/descendant::input'
    LIST_OF_TIME_IN_FORCE_XPATH = '//*[@id="select-good-list"]//span[text()="{}"]'
    EXPIRE_DATE_FIELD_XPATH = '//*[text()="Expire Date"]/following-sibling::span//input'
    BUY_BUTTON_XPATH = '//*[@class="buttons"]/button'
    SELL_BUTTON_XPATH = '//*[@class="buttons"]/button'
    CLOSE_BUTTON_XPATH = '//*[@id="order"]/igx-icon'
    NOTIFICATION_ACCOUNT_XPATH = '//*[@class="notification-without-title"]'