class Constants:
    class MainPage:
        PAGE_TITLE = '//span[@class="entity-title left"][normalize-space()="Account Lists"]'
        REFRESH_PAGE_BUTTON = '//*[@data-name="refresh"]'
        DOWNLOAD_PDF_BUTTON = '//nb-icon[@icon="download-outline"]//*[@data-name="download"]'
        OK_BUTTON = '//*[normalize-space()="Ok" or normalize-space()="OK"]'
        CANCEL_BUTTON = '//*[normalize-space()="Cancel"]'
        MORE_ACTIONS_BUTTON = '//*[@data-name = "more-vertical"]'
        EDIT_BUTTON = '//*[@data-name="edit"]'
        CLONE_BUTTON = '//*[@data-name="copy"]'
        DELETE_BUTTON = '//*[@data-name="trash-2"]'
        PIN_ROW_BUTTON = '//*[@nbtooltip="Click to Pin Row"]'
        NEW_BUTTON = '//*[normalize-space()="Account Lists"]//..//*[normalize-space()="New"]'
        DISPLAYED_ACCOUNT_LIST = '//*[text()="{}"]'

        GLOBAL_FILTER = '//app-header-index-view//*[@placeholder="Filter"]'
        NAME_FILTER = '//div[@style="width: 200px; left: 0px;"]//input[@ref="eFloatingFilterText"]'

    class Wizard:
        SAVE_CHANGES_BUTTON = '//*[normalize-space()="Save Changes"]'
        CLEAR_CHANGES_BUTTON = '//*[normalize-space()="Clear Changes"]'
        REVERT_CHANGES = '//*[normalize-space()="Revert Changes"]'
        CLOSE_WIZARD_BUTTON = '//*[@data-name="close"]'
        DOWNLOAD_PDF_BUTTON = '//*[@icon="download-outline"]'
        OK_BUTTON = '//*[normalize-space()="Ok" or normalize-space()="OK"]'
        CANCEL_BUTTON = '//*[normalize-space()="Cancel"]'
        NO_BUTTON = '//button[normalize-space()="No"]'

        ACCOUNT_LIST_NAME = '//*[@formcontrolname="accountListName"]'
        PLUS_BUTTON = '//*[@data-name="plus"]'
        CHECKMARK_BUTTON = '//*[@data-name="checkmark"]'
        CLOSE_BUTTON = '//*[@data-name="close"]'
        EDIT_BUTTON = '//*[@data-name="edit"]'
        DELETE_BUTTON = '//*[@data-name="trash-2"]'
        ACCOUNT_FILTER = '//app-inline-table//input[@placeholder="Filter"]'
        ACCOUNT = '//*[@id="account"]'
        DISPLAYED_ACCOUNTS_IN_TABLE = '//tbody//div//span'
        FOOTER_WARNING_MESSAGE = '//nb-alert//span'
        ACCOUNT_LINK_NAME = '//*[normalize-space()="Account"]//..//a'
