#region Order Book
ORDER_BOOK_BUTTON_XPATH = '//*[@class="container"]//button[5]'
SWITCH_BUTTON_XPATH = '//*[@class="igx-switch__composite"]'
MAXIMIZE_BUTTON_XPATH = ''
MINIMIZE_BUTTON_XPATH = ''
CLOSE_BUTTON_XPATH = ''
COPY_PANAL_BUTTON_XPATH = '//*[@class="copy-workspace-icon"]/img'
FIELD_CHOOSER_XPATH = '//*[@name="btnColumnHiding"]'
ADVANCED_FILTERING_BUTTON_XPATH = '//*[@name="btnAdvancedFiltering"]'
SYMBOL_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_0"]'
SORT_SYMBOL_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_0"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_SYMBOL_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_0"]//div[contains(@class, "igx-excel-filter__icon")]'
INSTR_TYPE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_1"]'
SORT_INSTR_TYPE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_1"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_INSTR_TYPE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_1"]//div[contains(@class, "igx-excel-filter__icon")]'
ORDER_ID_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_2"]'
SORT_ORDER_ID_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_2"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_ORDER_ID_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_2"]//div[contains(@class, "igx-excel-filter__icon")]'
ACCOUNT_CODE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_3"]'
SORT_ACCOUNT_CODE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_3"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_ACCOUNT_CODE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_3"]//div[contains(@class, "igx-excel-filter__icon")]'
SIDE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_4"]'
SORT_SIDE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_4"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_SIDE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_4"]//div[contains(@class, "igx-excel-filter__icon")]'
ORDER_QTY_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_5"]'
SORT_ORDER_QTY_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_5"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_ORDER_QTY_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_5"]//div[contains(@class, "igx-excel-filter__icon")]'
PRICE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_6"]'
SORT_PRICE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_6"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_PRICE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_6"]//div[contains(@class, "igx-excel-filter__icon")]'
AVG_PRICE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_7"]'
SORT_AVG_PRICE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_7"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_AVG_PRICE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_7"]//div[contains(@class, "igx-excel-filter__icon")]'
LEAVES_QTY_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_8"]'
SORT_LEAVES_QTY_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_8"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_LEAVES_QTY_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_8"]//div[contains(@class, "igx-excel-filter__icon")]'
ORDER_TYPE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_9"]'
SORT_ORDER_TYPE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_9"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_ORDER_TYPE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_9"]//div[contains(@class, "igx-excel-filter__icon")]'
CUM_QTY_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_10"]'
SORT_CUM_QTY_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_10"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_CUM_QTY_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_10"]//div[contains(@class, "igx-excel-filter__icon")]'
ORDER_STATUS_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_11"]'
SORT_ORDER_STATUS_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_11"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_ORDER_STATUS_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_11"]//div[contains(@class, "igx-excel-filter__icon")]'
EXPIRE_DATE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_12"]'
SORT_EXPIRE_DATE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_12"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_EXPIRE_DATE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_12"]//div[contains(@class, "igx-excel-filter__icon")]'
SETTLE_DATE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_13"]'
SORT_SETTLE_DATE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_13"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_SETTLE_DATE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_13"]//div[contains(@class, "igx-excel-filter__icon")]'
SETTLE_TYPE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_14"]'
SORT_SETTLE_TYPE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_14"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_SETTLE_TYPE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_14"]//div[contains(@class, "igx-excel-filter__icon")]'
TIME_IN_FORCE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_15"]'
SORT_TIME_IN_FORCE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_15"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_TIME_IN_FORCE_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_15"]//div[contains(@class, "igx-excel-filter__icon")]'
FREE_NOTES_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_16"]'
SORT_FREE_NOTES_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_16"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_FREE_NOTES_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_16"]//div[contains(@class, "igx-excel-filter__icon")]'
ACCOUNT_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_17"]'
SORT_ACCOUNT_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_17"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_ACCOUNT_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_17"]//div[contains(@class, "igx-excel-filter__icon")]'
TRANSACTION_TIME_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_18"]'
SORT_TRANSACTION_TIME_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_18"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_TRANSACTION_TIME_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_18"]//div[contains(@class, "igx-excel-filter__icon")]'
CIORDID_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_19"]'
SORT_CIORDID_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_19"]//igx-icon[contains(@class, "sort-icon")]'
FILTER_CIORDID_COLUMN_XPATH = '//*[@id="igx-grid-0_-1_0_19"]//div[contains(@class, "igx-excel-filter__icon")]'
ORDER_SYMBOL_XPATH = '//*[@id="igx-grid-0_0_0"]'
ORDER_INSTR_TYPE_XPATH = '//*[@id="igx-grid-0_0_1"]'
ORDER_ORDER_ID_XPATH = '//*[@id="igx-grid-0_0_2"]'
ORDER_ACCOUNT_CODE_XPATH = '//*[@id="igx-grid-0_0_3"]'
ORDER_SIDE_XPATH = '//*[@id="igx-grid-0_0_4"]'
ORDER_ORDER_QTY_XPATH = '//*[@id="igx-grid-0_0_5"]'
ORDER_PRICE_XPATH = '//*[@id="igx-grid-0_0_6"]'
ORDER_AVG_PRICE_XPATH = '//*[@id="igx-grid-0_0_7"]'
ORDER_LEAVES_QTY_XPATH = '//*[@id="igx-grid-0_0_8"]'
ORDER_ORDER_TYPE_XPATH = '//*[@id="igx-grid-0_0_9"]'
ORDER_CUM_QTY_XPATH = '//*[@id="igx-grid-0_0_10"]'
ORDER_ORDER_STATUS_XPATH = '//*[@id="igx-grid-0_0_11"]'
ORDER_EXPIRE_DATE_XPATH = '//*[@id="igx-grid-0_0_12"]'
ORDER_SETTLE_DATE_XPATH = '//*[@id="igx-grid-0_0_13"]'
ORDER_SETTLE_TYPE_XPATH = '//*[@id="igx-grid-0_0_14"]'
ORDER_TIME_IN_FORCE_XPATH = '//*[@id="igx-grid-0_0_15"]'
ORDER_FREE_NOTES_XPATH = '//*[@id="igx-grid-0_0_16"]'
ORDER_ACCOUNT_XPATH = '//*[@id="igx-grid-0_0_17"]'
ORDER_TRANSACTION_TIME_XPATH = '//*[@id="igx-grid-0_0_18"]'
ORDER_CIORDID_XPATH = '//*[@id="igx-grid-0_0_19"]'
HORIZONTAL_SCROLL_XPATH = '//*[@class="igx-vhelper--horizontal ng-star-inserted"]/div[@class="igx-vhelper__placeholder-content"]'
#endregion

#region Switch field
FROM_FIELD_XPATH = '//*[@aria-labelledby="igx-label-8"]'
TO_FIELD_XPATH = '//*[@aria-labelledby="igx-label-9"]'
CANSEL_FROM_BUTTON_XPATH = '//*[@id="igx-date-picker-8"]//*[@class="ng-star-inserted"][2]'
CANSEL_TO_BUTTON_XPATH = '//*[@id="igx-date-picker-9"]//*[@class="ng-star-inserted"][2]'
SEARCH_XPATH = '//*[text()="Search"]'
#endregion

#region Field chooser
FILTER_COLUMNS_LIST_FIELD_XPATH = '//*[@id="igx-column-actions-0"]//input'
SYMBOL_CHECKBOX_XPATH = '//*[@id="igx-checkbox-0-label"]'
HIDE_ALL_BUTTON_XPATH = '//*[text()="Hide All"]'
SHOW_ALL_BUTTON_XPATH = '//*[text()="Show All"]'
#endregion

#region Advanced filtering
DRAG_ADVANCED_FILTERING_WINDOW_XPATH = '//*[@class="igx-overlay__wrapper"]//header'
AND_GROUP_BUTTON_XPATH = '//*[@class="igx-advanced-filter__main"]/button[1]'
OR_GROUP_BUTTON_XPATH = '//*[@class="igx-advanced-filter__main"]/button[2]'
CLEAR_FILTER_BUTTON_XPATH = '//*[@class="igx-excel-filter__clear"]/button'
CANCEL_BUTTON_XPATH = '//*[@class="igx-excel-filter__cancel"]/button'
APPLY_BUTTON_XPATH = '//*[@class="igx-excel-filter__apply"]/button'
BACK_LINE_BUTTON_XPATH = '//*[contains(@class,"igx-filter-tree__line")]'
SELECT_COLUMN_FIELD_XPATH = '//*[contains(@class,"igx-filter-tree__inputs ng-star-inserted")]/igx-select[1]'
SELECT_COLUMN_SYMBOL_XPATH = '//*[@id="igx-drop-down-item-60"]'
SELECT_FILTER_FIELD_XPATH = '//*[contains(@class,"igx-filter-tree__inputs ng-star-inserted")]/igx-select[2]'
SELECT_FILTER_CONTAINS_XPATH = '//*[@id="igx-drop-down-item-80"]'
VALUE_FIELD_XPATH = '//*[contains(@class,"igx-filter-tree__inputs ng-star-inserted")]/igx-input-group'
CHECK_AF_BUTTON_XPATH = '//*[contains(@class,"igx-filter-tree__inputs ng-star-inserted")]//button[1]'
CLOSE_AF_BUTTON_XPATH = '//*[contains(@class,"igx-filter-tree__inputs ng-star-inserted")]//button[2]'
CONDITION_BUTTON_XPATH = '//*[contains(@class,"igx-filter-tree__buttons ng-star-inserted")]//button[1]'
AND_BUTTON_XPATH = '//*[contains(@class,"igx-filter-tree__buttons ng-star-inserted")]//button[2]'
OR_BUTTON_XPATH = '//*[contains(@class,"igx-filter-tree__buttons ng-star-inserted")]//button[3]'
#endregion

#region Filter
PIN_BUTTON_XPATH = '//*[@aria-label="Pin column"]'
HIDE_BUTTON_XPATH = '//*[@aria-label="Hide column"]'
SEARCH_FIELD_XPATH = '//*[@class="igx-excel-filter__menu-main"]/igx-input-group'
SELECT_ALL_CHECKBOX_XPATH = '//*[@id="igx-checkbox-135-input"]'
CANCEL_XPATH = '//*[@class="igx-excel-filter__cancel"]'
APPLY_XPATH = '//*[@class="igx-excel-filter__apply"]'
#endregion