# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: act_fix.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import grpc_modules.infra_pb2 as infra__pb2
import grpc_modules.event_store_pb2 as event__store__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='act_fix.proto',
  package='th2',
  syntax='proto3',
  serialized_options=_b('\n\031com.exactpro.th2.act.grpcP\001'),
  serialized_pb=_b('\n\ract_fix.proto\x12\x03th2\x1a\x0binfra.proto\x1a\x11\x65vent-store.proto\"a\n\x13SendMessageResponse\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.th2.RequestStatus\x12&\n\rcheckpoint_id\x18\x02 \x01(\x0b\x32\x0f.th2.Checkpoint\"\x89\x02\n\x13PlaceMessageRequest\x12\x1d\n\x07message\x18\x01 \x01(\x0b\x32\x0c.th2.Message\x12(\n\rconnection_id\x18\x02 \x01(\x0b\x32\x11.th2.ConnectionID\x12%\n\x0fparent_event_id\x18\x04 \x01(\x0b\x32\x0c.th2.EventID\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12;\n\nkey_fields\x18\x06 \x03(\x0b\x32\'.th2.PlaceMessageRequest.KeyFieldsEntry\x1a\x30\n\x0eKeyFieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8a\x01\n\x14PlaceMessageResponse\x12&\n\x10response_message\x18\x01 \x01(\x0b\x32\x0c.th2.Message\x12\"\n\x06status\x18\x02 \x01(\x0b\x32\x12.th2.RequestStatus\x12&\n\rcheckpoint_id\x18\x03 \x01(\x0b\x32\x0f.th2.Checkpoint2\xcb\x05\n\x03\x41\x63t\x12\x43\n\x0bsendMessage\x12\x18.th2.PlaceMessageRequest\x1a\x18.th2.SendMessageResponse\"\x00\x12\x46\n\rplaceOrderFIX\x12\x18.th2.PlaceMessageRequest\x1a\x19.th2.PlaceMessageResponse\"\x00\x12M\n\x14placeOrderReplaceFIX\x12\x18.th2.PlaceMessageRequest\x1a\x19.th2.PlaceMessageResponse\"\x00\x12L\n\x13placeOrderCancelFIX\x12\x18.th2.PlaceMessageRequest\x1a\x19.th2.PlaceMessageResponse\"\x00\x12N\n\x15placeOrderMultilegFIX\x12\x18.th2.PlaceMessageRequest\x1a\x19.th2.PlaceMessageResponse\"\x00\x12U\n\x1cplaceOrderMultilegReplaceFIX\x12\x18.th2.PlaceMessageRequest\x1a\x19.th2.PlaceMessageResponse\"\x00\x12\x46\n\rplaceQuoteFIX\x12\x18.th2.PlaceMessageRequest\x1a\x19.th2.PlaceMessageResponse\"\x00\x12R\n\x19placeMarketDataRequestFIX\x12\x18.th2.PlaceMessageRequest\x1a\x19.th2.PlaceMessageResponse\"\x00\x12W\n\x1eplaceOrderMassCancelRequestFIX\x12\x18.th2.PlaceMessageRequest\x1a\x19.th2.PlaceMessageResponse\"\x00\x42\x1d\n\x19\x63om.exactpro.th2.act.grpcP\x01\x62\x06proto3')
  ,
  dependencies=[infra__pb2.DESCRIPTOR,event__store__pb2.DESCRIPTOR,])




_SENDMESSAGERESPONSE = _descriptor.Descriptor(
  name='SendMessageResponse',
  full_name='th2.SendMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='th2.SendMessageResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkpoint_id', full_name='th2.SendMessageResponse.checkpoint_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=151,
)


_PLACEMESSAGEREQUEST_KEYFIELDSENTRY = _descriptor.Descriptor(
  name='KeyFieldsEntry',
  full_name='th2.PlaceMessageRequest.KeyFieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='th2.PlaceMessageRequest.KeyFieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='th2.PlaceMessageRequest.KeyFieldsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=419,
)

_PLACEMESSAGEREQUEST = _descriptor.Descriptor(
  name='PlaceMessageRequest',
  full_name='th2.PlaceMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='th2.PlaceMessageRequest.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection_id', full_name='th2.PlaceMessageRequest.connection_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_event_id', full_name='th2.PlaceMessageRequest.parent_event_id', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='th2.PlaceMessageRequest.description', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_fields', full_name='th2.PlaceMessageRequest.key_fields', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PLACEMESSAGEREQUEST_KEYFIELDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=419,
)


_PLACEMESSAGERESPONSE = _descriptor.Descriptor(
  name='PlaceMessageResponse',
  full_name='th2.PlaceMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_message', full_name='th2.PlaceMessageResponse.response_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='th2.PlaceMessageResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkpoint_id', full_name='th2.PlaceMessageResponse.checkpoint_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=560,
)

_SENDMESSAGERESPONSE.fields_by_name['status'].message_type = infra__pb2._REQUESTSTATUS
_SENDMESSAGERESPONSE.fields_by_name['checkpoint_id'].message_type = infra__pb2._CHECKPOINT
_PLACEMESSAGEREQUEST_KEYFIELDSENTRY.containing_type = _PLACEMESSAGEREQUEST
_PLACEMESSAGEREQUEST.fields_by_name['message'].message_type = infra__pb2._MESSAGE
_PLACEMESSAGEREQUEST.fields_by_name['connection_id'].message_type = infra__pb2._CONNECTIONID
_PLACEMESSAGEREQUEST.fields_by_name['parent_event_id'].message_type = infra__pb2._EVENTID
_PLACEMESSAGEREQUEST.fields_by_name['key_fields'].message_type = _PLACEMESSAGEREQUEST_KEYFIELDSENTRY
_PLACEMESSAGERESPONSE.fields_by_name['response_message'].message_type = infra__pb2._MESSAGE
_PLACEMESSAGERESPONSE.fields_by_name['status'].message_type = infra__pb2._REQUESTSTATUS
_PLACEMESSAGERESPONSE.fields_by_name['checkpoint_id'].message_type = infra__pb2._CHECKPOINT
DESCRIPTOR.message_types_by_name['SendMessageResponse'] = _SENDMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['PlaceMessageRequest'] = _PLACEMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['PlaceMessageResponse'] = _PLACEMESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendMessageResponse = _reflection.GeneratedProtocolMessageType('SendMessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDMESSAGERESPONSE,
  __module__ = 'act_fix_pb2'
  # @@protoc_insertion_point(class_scope:th2.SendMessageResponse)
  ))
_sym_db.RegisterMessage(SendMessageResponse)

PlaceMessageRequest = _reflection.GeneratedProtocolMessageType('PlaceMessageRequest', (_message.Message,), dict(

  KeyFieldsEntry = _reflection.GeneratedProtocolMessageType('KeyFieldsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PLACEMESSAGEREQUEST_KEYFIELDSENTRY,
    __module__ = 'act_fix_pb2'
    # @@protoc_insertion_point(class_scope:th2.PlaceMessageRequest.KeyFieldsEntry)
    ))
  ,
  DESCRIPTOR = _PLACEMESSAGEREQUEST,
  __module__ = 'act_fix_pb2'
  # @@protoc_insertion_point(class_scope:th2.PlaceMessageRequest)
  ))
_sym_db.RegisterMessage(PlaceMessageRequest)
_sym_db.RegisterMessage(PlaceMessageRequest.KeyFieldsEntry)

PlaceMessageResponse = _reflection.GeneratedProtocolMessageType('PlaceMessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _PLACEMESSAGERESPONSE,
  __module__ = 'act_fix_pb2'
  # @@protoc_insertion_point(class_scope:th2.PlaceMessageResponse)
  ))
_sym_db.RegisterMessage(PlaceMessageResponse)


DESCRIPTOR._options = None
_PLACEMESSAGEREQUEST_KEYFIELDSENTRY._options = None

_ACT = _descriptor.ServiceDescriptor(
  name='Act',
  full_name='th2.Act',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=563,
  serialized_end=1278,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='th2.Act.sendMessage',
    index=0,
    containing_service=None,
    input_type=_PLACEMESSAGEREQUEST,
    output_type=_SENDMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='placeOrderFIX',
    full_name='th2.Act.placeOrderFIX',
    index=1,
    containing_service=None,
    input_type=_PLACEMESSAGEREQUEST,
    output_type=_PLACEMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='placeOrderReplaceFIX',
    full_name='th2.Act.placeOrderReplaceFIX',
    index=2,
    containing_service=None,
    input_type=_PLACEMESSAGEREQUEST,
    output_type=_PLACEMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='placeOrderCancelFIX',
    full_name='th2.Act.placeOrderCancelFIX',
    index=3,
    containing_service=None,
    input_type=_PLACEMESSAGEREQUEST,
    output_type=_PLACEMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='placeOrderMultilegFIX',
    full_name='th2.Act.placeOrderMultilegFIX',
    index=4,
    containing_service=None,
    input_type=_PLACEMESSAGEREQUEST,
    output_type=_PLACEMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='placeOrderMultilegReplaceFIX',
    full_name='th2.Act.placeOrderMultilegReplaceFIX',
    index=5,
    containing_service=None,
    input_type=_PLACEMESSAGEREQUEST,
    output_type=_PLACEMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='placeQuoteFIX',
    full_name='th2.Act.placeQuoteFIX',
    index=6,
    containing_service=None,
    input_type=_PLACEMESSAGEREQUEST,
    output_type=_PLACEMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='placeMarketDataRequestFIX',
    full_name='th2.Act.placeMarketDataRequestFIX',
    index=7,
    containing_service=None,
    input_type=_PLACEMESSAGEREQUEST,
    output_type=_PLACEMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='placeOrderMassCancelRequestFIX',
    full_name='th2.Act.placeOrderMassCancelRequestFIX',
    index=8,
    containing_service=None,
    input_type=_PLACEMESSAGEREQUEST,
    output_type=_PLACEMESSAGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACT)

DESCRIPTOR.services_by_name['Act'] = _ACT

# @@protoc_insertion_point(module_scope)
