# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import grpc_modules.infra_pb2 as infra__pb2
import grpc_modules.rhbatch_pb2 as rhbatch__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='th2',
  syntax='proto3',
  serialized_options=_b('\n\031com.exactpro.th2.act.grpcP\001'),
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x03th2\x1a\x0binfra.proto\x1a\rrhbatch.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n\x0b\x42\x61seRequest\x12#\n\tsessionID\x18\x01 \x01(\x0b\x32\x10.th2.RhSessionID\x12#\n\rparentEventId\x18\x02 \x01(\x0b\x32\x0c.th2.EventID\"\xcf\x02\n\x0b\x41\x63tResponse\x12\x36\n\x0cscriptStatus\x18\x01 \x01(\x0e\x32 .th2.ActResponse.ExecutionStatus\x12\x12\n\nstatusInfo\x18\x02 \x01(\t\x12\x11\n\terrorInfo\x18\x03 \x01(\t\x12(\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x1a.th2.ActResponse.DataEntry\x12#\n\tsessionID\x18\x05 \x01(\x0b\x32\x10.th2.RhSessionID\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"e\n\x0f\x45xecutionStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\r\n\tACT_ERROR\x10\x01\x12\x0e\n\nHAND_ERROR\x10\x02\x12\x11\n\rCOMPILE_ERROR\x10\x03\x12\x13\n\x0f\x45XECUTION_ERROR\x10\x04\x42\x1d\n\x19\x63om.exactpro.th2.act.grpcP\x01\x62\x06proto3')
  ,
  dependencies=[infra__pb2.DESCRIPTOR,rhbatch__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_ACTRESPONSE_EXECUTIONSTATUS = _descriptor.EnumDescriptor(
  name='ExecutionStatus',
  full_name='th2.ActResponse.ExecutionStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACT_ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HAND_ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPILE_ERROR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXECUTION_ERROR', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=406,
  serialized_end=507,
)
_sym_db.RegisterEnumDescriptor(_ACTRESPONSE_EXECUTIONSTATUS)


_BASEREQUEST = _descriptor.Descriptor(
  name='BaseRequest',
  full_name='th2.BaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionID', full_name='th2.BaseRequest.sessionID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parentEventId', full_name='th2.BaseRequest.parentEventId', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=169,
)


_ACTRESPONSE_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='th2.ActResponse.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='th2.ActResponse.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='th2.ActResponse.DataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=404,
)

_ACTRESPONSE = _descriptor.Descriptor(
  name='ActResponse',
  full_name='th2.ActResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scriptStatus', full_name='th2.ActResponse.scriptStatus', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statusInfo', full_name='th2.ActResponse.statusInfo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorInfo', full_name='th2.ActResponse.errorInfo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='th2.ActResponse.data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionID', full_name='th2.ActResponse.sessionID', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ACTRESPONSE_DATAENTRY, ],
  enum_types=[
    _ACTRESPONSE_EXECUTIONSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=507,
)

_BASEREQUEST.fields_by_name['sessionID'].message_type = rhbatch__pb2._RHSESSIONID
_BASEREQUEST.fields_by_name['parentEventId'].message_type = infra__pb2._EVENTID
_ACTRESPONSE_DATAENTRY.containing_type = _ACTRESPONSE
_ACTRESPONSE.fields_by_name['scriptStatus'].enum_type = _ACTRESPONSE_EXECUTIONSTATUS
_ACTRESPONSE.fields_by_name['data'].message_type = _ACTRESPONSE_DATAENTRY
_ACTRESPONSE.fields_by_name['sessionID'].message_type = rhbatch__pb2._RHSESSIONID
_ACTRESPONSE_EXECUTIONSTATUS.containing_type = _ACTRESPONSE
DESCRIPTOR.message_types_by_name['BaseRequest'] = _BASEREQUEST
DESCRIPTOR.message_types_by_name['ActResponse'] = _ACTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseRequest = _reflection.GeneratedProtocolMessageType('BaseRequest', (_message.Message,), dict(
  DESCRIPTOR = _BASEREQUEST,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:th2.BaseRequest)
  ))
_sym_db.RegisterMessage(BaseRequest)

ActResponse = _reflection.GeneratedProtocolMessageType('ActResponse', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _ACTRESPONSE_DATAENTRY,
    __module__ = 'common_pb2'
    # @@protoc_insertion_point(class_scope:th2.ActResponse.DataEntry)
    ))
  ,
  DESCRIPTOR = _ACTRESPONSE,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:th2.ActResponse)
  ))
_sym_db.RegisterMessage(ActResponse)
_sym_db.RegisterMessage(ActResponse.DataEntry)


DESCRIPTOR._options = None
_ACTRESPONSE_DATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
