# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connectivity.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connectivity.proto',
  package='th2',
  syntax='proto3',
  serialized_options=b'\n\"com.exactpro.th2.connectivity.grpcP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63onnectivity.proto\x12\x03th2\"\x0e\n\x0cQueueRequest\"\xb8\x01\n\tQueueInfo\x12\x15\n\rexchange_name\x18\x01 \x01(\t\x12\x14\n\x0cin_msg_queue\x18\x02 \x01(\t\x12\x18\n\x10in_raw_msg_queue\x18\x03 \x01(\t\x12\x15\n\rout_msg_queue\x18\x04 \x01(\t\x12\x19\n\x11out_raw_msg_queue\x18\x05 \x01(\t\x12\x16\n\x0esend_msg_queue\x18\x06 \x01(\t\x12\x1a\n\x12send_raw_msg_queue\x18\x07 \x01(\t2C\n\x0c\x43onnectivity\x12\x33\n\x0cgetQueueInfo\x12\x11.th2.QueueRequest\x1a\x0e.th2.QueueInfo\"\x00\x42&\n\"com.exactpro.th2.connectivity.grpcP\x01\x62\x06proto3'
)




_QUEUEREQUEST = _descriptor.Descriptor(
  name='QueueRequest',
  full_name='th2.QueueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=41,
)


_QUEUEINFO = _descriptor.Descriptor(
  name='QueueInfo',
  full_name='th2.QueueInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange_name', full_name='th2.QueueInfo.exchange_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='in_msg_queue', full_name='th2.QueueInfo.in_msg_queue', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='in_raw_msg_queue', full_name='th2.QueueInfo.in_raw_msg_queue', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='out_msg_queue', full_name='th2.QueueInfo.out_msg_queue', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='out_raw_msg_queue', full_name='th2.QueueInfo.out_raw_msg_queue', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='send_msg_queue', full_name='th2.QueueInfo.send_msg_queue', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='send_raw_msg_queue', full_name='th2.QueueInfo.send_raw_msg_queue', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=228,
)

DESCRIPTOR.message_types_by_name['QueueRequest'] = _QUEUEREQUEST
DESCRIPTOR.message_types_by_name['QueueInfo'] = _QUEUEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueueRequest = _reflection.GeneratedProtocolMessageType('QueueRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUEUEREQUEST,
  '__module__' : 'connectivity_pb2'
  # @@protoc_insertion_point(class_scope:th2.QueueRequest)
  })
_sym_db.RegisterMessage(QueueRequest)

QueueInfo = _reflection.GeneratedProtocolMessageType('QueueInfo', (_message.Message,), {
  'DESCRIPTOR' : _QUEUEINFO,
  '__module__' : 'connectivity_pb2'
  # @@protoc_insertion_point(class_scope:th2.QueueInfo)
  })
_sym_db.RegisterMessage(QueueInfo)


DESCRIPTOR._options = None

_CONNECTIVITY = _descriptor.ServiceDescriptor(
  name='Connectivity',
  full_name='th2.Connectivity',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=230,
  serialized_end=297,
  methods=[
  _descriptor.MethodDescriptor(
    name='getQueueInfo',
    full_name='th2.Connectivity.getQueueInfo',
    index=0,
    containing_service=None,
    input_type=_QUEUEREQUEST,
    output_type=_QUEUEINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECTIVITY)

DESCRIPTOR.services_by_name['Connectivity'] = _CONNECTIVITY

# @@protoc_insertion_point(module_scope)
