# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event-store.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import grpc_modules.infra_pb2 as infra__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event-store.proto',
  package='th2',
  syntax='proto3',
  serialized_options=b'\n com.exactpro.th2.eventstore.grpcP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x65vent-store.proto\x12\x03th2\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0binfra.proto\".\n\x11StoreEventRequest\x12\x19\n\x05\x65vent\x18\x01 \x01(\x0b\x32\n.th2.Event\">\n\x16StoreEventBatchRequest\x12$\n\x0b\x65vent_batch\x18\x01 \x01(\x0b\x32\x0f.th2.EventBatch\"a\n\x08Response\x12+\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12(\n\x02id\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue2\x87\x01\n\x11\x45ventStoreService\x12\x33\n\nStoreEvent\x12\x16.th2.StoreEventRequest\x1a\r.th2.Response\x12=\n\x0fStoreEventBatch\x12\x1b.th2.StoreEventBatchRequest\x1a\r.th2.ResponseB$\n com.exactpro.th2.eventstore.grpcP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,infra__pb2.DESCRIPTOR,])




_STOREEVENTREQUEST = _descriptor.Descriptor(
  name='StoreEventRequest',
  full_name='th2.StoreEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='th2.StoreEventRequest.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=177,
)


_STOREEVENTBATCHREQUEST = _descriptor.Descriptor(
  name='StoreEventBatchRequest',
  full_name='th2.StoreEventBatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_batch', full_name='th2.StoreEventBatchRequest.event_batch', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=241,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='th2.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='th2.Response.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='th2.Response.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=340,
)

_STOREEVENTREQUEST.fields_by_name['event'].message_type = infra__pb2._EVENT
_STOREEVENTBATCHREQUEST.fields_by_name['event_batch'].message_type = infra__pb2._EVENTBATCH
_RESPONSE.fields_by_name['error'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_RESPONSE.fields_by_name['id'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
DESCRIPTOR.message_types_by_name['StoreEventRequest'] = _STOREEVENTREQUEST
DESCRIPTOR.message_types_by_name['StoreEventBatchRequest'] = _STOREEVENTBATCHREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StoreEventRequest = _reflection.GeneratedProtocolMessageType('StoreEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOREEVENTREQUEST,
  '__module__' : 'event_store_pb2'
  # @@protoc_insertion_point(class_scope:th2.StoreEventRequest)
  })
_sym_db.RegisterMessage(StoreEventRequest)

StoreEventBatchRequest = _reflection.GeneratedProtocolMessageType('StoreEventBatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOREEVENTBATCHREQUEST,
  '__module__' : 'event_store_pb2'
  # @@protoc_insertion_point(class_scope:th2.StoreEventBatchRequest)
  })
_sym_db.RegisterMessage(StoreEventBatchRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'event_store_pb2'
  # @@protoc_insertion_point(class_scope:th2.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_EVENTSTORESERVICE = _descriptor.ServiceDescriptor(
  name='EventStoreService',
  full_name='th2.EventStoreService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=343,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='StoreEvent',
    full_name='th2.EventStoreService.StoreEvent',
    index=0,
    containing_service=None,
    input_type=_STOREEVENTREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StoreEventBatch',
    full_name='th2.EventStoreService.StoreEventBatch',
    index=1,
    containing_service=None,
    input_type=_STOREEVENTBATCHREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTSTORESERVICE)

DESCRIPTOR.services_by_name['EventStoreService'] = _EVENTSTORESERVICE

# @@protoc_insertion_point(module_scope)
