# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_modules.common_pb2 as common__pb2
import grpc_modules.order_ticket_pb2 as order__ticket__pb2


class OrderTicketServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.placeOrder = channel.unary_unary(
        '/th2.OrderTicketService/placeOrder',
        request_serializer=order__ticket__pb2.NewOrderDetails.SerializeToString,
        response_deserializer=common__pb2.ActResponse.FromString,
        )


class OrderTicketServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def placeOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderTicketServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'placeOrder': grpc.unary_unary_rpc_method_handler(
          servicer.placeOrder,
          request_deserializer=order__ticket__pb2.NewOrderDetails.FromString,
          response_serializer=common__pb2.ActResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'th2.OrderTicketService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
