# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_modules.common_pb2 as common__pb2
import grpc_modules.order_book_pb2 as order__book__pb2


class OrderBookServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.amendOrder = channel.unary_unary(
        '/th2.OrderBookService/amendOrder',
        request_serializer=order__book__pb2.ModifyOrderDetails.SerializeToString,
        response_deserializer=common__pb2.ActResponse.FromString,
        )
    self.splitOrder = channel.unary_unary(
        '/th2.OrderBookService/splitOrder',
        request_serializer=order__book__pb2.ModifyOrderDetails.SerializeToString,
        response_deserializer=common__pb2.ActResponse.FromString,
        )
    self.splitLimit = channel.unary_unary(
        '/th2.OrderBookService/splitLimit',
        request_serializer=order__book__pb2.ModifyOrderDetails.SerializeToString,
        response_deserializer=common__pb2.ActResponse.FromString,
        )
    self.cancelOrder = channel.unary_unary(
        '/th2.OrderBookService/cancelOrder',
        request_serializer=order__book__pb2.CancelOrderDetails.SerializeToString,
        response_deserializer=common__pb2.ActResponse.FromString,
        )
    self.getOrdersDetails = channel.unary_unary(
        '/th2.OrderBookService/getOrdersDetails',
        request_serializer=order__book__pb2.GetOrdersDetailsRequest.SerializeToString,
        response_deserializer=common__pb2.ActResponse.FromString,
        )


class OrderBookServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def amendOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def splitOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def splitLimit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def cancelOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getOrdersDetails(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderBookServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'amendOrder': grpc.unary_unary_rpc_method_handler(
          servicer.amendOrder,
          request_deserializer=order__book__pb2.ModifyOrderDetails.FromString,
          response_serializer=common__pb2.ActResponse.SerializeToString,
      ),
      'splitOrder': grpc.unary_unary_rpc_method_handler(
          servicer.splitOrder,
          request_deserializer=order__book__pb2.ModifyOrderDetails.FromString,
          response_serializer=common__pb2.ActResponse.SerializeToString,
      ),
      'splitLimit': grpc.unary_unary_rpc_method_handler(
          servicer.splitLimit,
          request_deserializer=order__book__pb2.ModifyOrderDetails.FromString,
          response_serializer=common__pb2.ActResponse.SerializeToString,
      ),
      'cancelOrder': grpc.unary_unary_rpc_method_handler(
          servicer.cancelOrder,
          request_deserializer=order__book__pb2.CancelOrderDetails.FromString,
          response_serializer=common__pb2.ActResponse.SerializeToString,
      ),
      'getOrdersDetails': grpc.unary_unary_rpc_method_handler(
          servicer.getOrdersDetails,
          request_deserializer=order__book__pb2.GetOrdersDetailsRequest.FromString,
          response_serializer=common__pb2.ActResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'th2.OrderBookService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
