# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quod_simulator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_modules import simulator_pb2 as simulator__pb2
from grpc_modules import infra_pb2 as infra__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='quod_simulator.proto',
  package='th2.simulator.template',
  syntax='proto3',
  serialized_options=_b('\n(com.exactpro.th2.simulator.template.grpcP\001'),
  serialized_pb=_b('\n\x14quod_simulator.proto\x12\x16th2.simulator.template\x1a\x0fsimulator.proto\x1a\x0binfra.proto\"\xbf\x01\n\x11TemplateFixCreate\x12\x45\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x35.th2.simulator.template.TemplateFixCreate.FieldsEntry\x12(\n\rconnection_id\x18\x02 \x01(\x0b\x32\x11.th2.ConnectionID\x1a\x39\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.th2.Value:\x02\x38\x01\"?\n\x13TemplateQuodNOSRule\x12(\n\rconnection_id\x18\x01 \x01(\x0b\x32\x11.th2.ConnectionID\"?\n\x13TemplateQuodOCRRule\x12(\n\rconnection_id\x18\x01 \x01(\x0b\x32\x11.th2.ConnectionID2\xda\x02\n\x18TemplateSimulatorService\x12J\n\x0e\x63reateRule_FIX\x12).th2.simulator.template.TemplateFixCreate\x1a\x0b.th2.RuleID\"\x00\x12P\n\x14\x63reateKotlinRule_FIX\x12).th2.simulator.template.TemplateFixCreate\x1a\x0b.th2.RuleID\"\x00\x12O\n\x11\x63reateQuodNOSRule\x12+.th2.simulator.template.TemplateQuodNOSRule\x1a\x0b.th2.RuleID\"\x00\x12O\n\x11\x63reateQuodOCRRule\x12+.th2.simulator.template.TemplateQuodOCRRule\x1a\x0b.th2.RuleID\"\x00\x42,\n(com.exactpro.th2.simulator.template.grpcP\x01\x62\x06proto3')
  ,
  dependencies=[simulator__pb2.DESCRIPTOR,infra__pb2.DESCRIPTOR,])




_TEMPLATEFIXCREATE_FIELDSENTRY = _descriptor.Descriptor(
  name='FieldsEntry',
  full_name='th2.simulator.template.TemplateFixCreate.FieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='th2.simulator.template.TemplateFixCreate.FieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='th2.simulator.template.TemplateFixCreate.FieldsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=270,
)

_TEMPLATEFIXCREATE = _descriptor.Descriptor(
  name='TemplateFixCreate',
  full_name='th2.simulator.template.TemplateFixCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='th2.simulator.template.TemplateFixCreate.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection_id', full_name='th2.simulator.template.TemplateFixCreate.connection_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TEMPLATEFIXCREATE_FIELDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=270,
)


_TEMPLATEQUODNOSRULE = _descriptor.Descriptor(
  name='TemplateQuodNOSRule',
  full_name='th2.simulator.template.TemplateQuodNOSRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connection_id', full_name='th2.simulator.template.TemplateQuodNOSRule.connection_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=335,
)


_TEMPLATEQUODOCRRULE = _descriptor.Descriptor(
  name='TemplateQuodOCRRule',
  full_name='th2.simulator.template.TemplateQuodOCRRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connection_id', full_name='th2.simulator.template.TemplateQuodOCRRule.connection_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=400,
)

_TEMPLATEFIXCREATE_FIELDSENTRY.fields_by_name['value'].message_type = infra__pb2._VALUE
_TEMPLATEFIXCREATE_FIELDSENTRY.containing_type = _TEMPLATEFIXCREATE
_TEMPLATEFIXCREATE.fields_by_name['fields'].message_type = _TEMPLATEFIXCREATE_FIELDSENTRY
_TEMPLATEFIXCREATE.fields_by_name['connection_id'].message_type = infra__pb2._CONNECTIONID
_TEMPLATEQUODNOSRULE.fields_by_name['connection_id'].message_type = infra__pb2._CONNECTIONID
_TEMPLATEQUODOCRRULE.fields_by_name['connection_id'].message_type = infra__pb2._CONNECTIONID
DESCRIPTOR.message_types_by_name['TemplateFixCreate'] = _TEMPLATEFIXCREATE
DESCRIPTOR.message_types_by_name['TemplateQuodNOSRule'] = _TEMPLATEQUODNOSRULE
DESCRIPTOR.message_types_by_name['TemplateQuodOCRRule'] = _TEMPLATEQUODOCRRULE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TemplateFixCreate = _reflection.GeneratedProtocolMessageType('TemplateFixCreate', (_message.Message,), dict(

  FieldsEntry = _reflection.GeneratedProtocolMessageType('FieldsEntry', (_message.Message,), dict(
    DESCRIPTOR = _TEMPLATEFIXCREATE_FIELDSENTRY,
    __module__ = 'quod_simulator_pb2'
    # @@protoc_insertion_point(class_scope:th2.simulator.template.TemplateFixCreate.FieldsEntry)
    ))
  ,
  DESCRIPTOR = _TEMPLATEFIXCREATE,
  __module__ = 'quod_simulator_pb2'
  # @@protoc_insertion_point(class_scope:th2.simulator.template.TemplateFixCreate)
  ))
_sym_db.RegisterMessage(TemplateFixCreate)
_sym_db.RegisterMessage(TemplateFixCreate.FieldsEntry)

TemplateQuodNOSRule = _reflection.GeneratedProtocolMessageType('TemplateQuodNOSRule', (_message.Message,), dict(
  DESCRIPTOR = _TEMPLATEQUODNOSRULE,
  __module__ = 'quod_simulator_pb2'
  # @@protoc_insertion_point(class_scope:th2.simulator.template.TemplateQuodNOSRule)
  ))
_sym_db.RegisterMessage(TemplateQuodNOSRule)

TemplateQuodOCRRule = _reflection.GeneratedProtocolMessageType('TemplateQuodOCRRule', (_message.Message,), dict(
  DESCRIPTOR = _TEMPLATEQUODOCRRULE,
  __module__ = 'quod_simulator_pb2'
  # @@protoc_insertion_point(class_scope:th2.simulator.template.TemplateQuodOCRRule)
  ))
_sym_db.RegisterMessage(TemplateQuodOCRRule)


DESCRIPTOR._options = None
_TEMPLATEFIXCREATE_FIELDSENTRY._options = None

_TEMPLATESIMULATORSERVICE = _descriptor.ServiceDescriptor(
  name='TemplateSimulatorService',
  full_name='th2.simulator.template.TemplateSimulatorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=403,
  serialized_end=749,
  methods=[
  _descriptor.MethodDescriptor(
    name='createRule_FIX',
    full_name='th2.simulator.template.TemplateSimulatorService.createRule_FIX',
    index=0,
    containing_service=None,
    input_type=_TEMPLATEFIXCREATE,
    output_type=simulator__pb2._RULEID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='createKotlinRule_FIX',
    full_name='th2.simulator.template.TemplateSimulatorService.createKotlinRule_FIX',
    index=1,
    containing_service=None,
    input_type=_TEMPLATEFIXCREATE,
    output_type=simulator__pb2._RULEID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='createQuodNOSRule',
    full_name='th2.simulator.template.TemplateSimulatorService.createQuodNOSRule',
    index=2,
    containing_service=None,
    input_type=_TEMPLATEQUODNOSRULE,
    output_type=simulator__pb2._RULEID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='createQuodOCRRule',
    full_name='th2.simulator.template.TemplateSimulatorService.createQuodOCRRule',
    index=3,
    containing_service=None,
    input_type=_TEMPLATEQUODOCRRULE,
    output_type=simulator__pb2._RULEID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPLATESIMULATORSERVICE)

DESCRIPTOR.services_by_name['TemplateSimulatorService'] = _TEMPLATESIMULATORSERVICE

# @@protoc_insertion_point(module_scope)
