# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_modules import quod_simulator_pb2 as quod__simulator__pb2
from grpc_modules import simulator_pb2 as simulator__pb2


class TemplateSimulatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createRule_FIX = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createRule_FIX',
                request_serializer=quod__simulator__pb2.TemplateFixCreate.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createKotlinRule_FIX = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createKotlinRule_FIX',
                request_serializer=quod__simulator__pb2.TemplateFixCreate.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createQuodNOSRule = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createQuodNOSRule',
                request_serializer=quod__simulator__pb2.TemplateQuodNOSRule.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createQuodOCRRule = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createQuodOCRRule',
                request_serializer=quod__simulator__pb2.TemplateQuodOCRRule.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createQuodOCRRRule = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createQuodOCRRRule',
                request_serializer=quod__simulator__pb2.TemplateQuodOCRRRule.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createQuodSingleExecRule = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createQuodSingleExecRule',
                request_serializer=quod__simulator__pb2.TemplateQuodSingleExecRule.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createQuodMDRRule = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createQuodMDRRule',
                request_serializer=quod__simulator__pb2.TemplateQuodMDRRule.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createQuodDefMDRRule = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createQuodDefMDRRule',
                request_serializer=quod__simulator__pb2.TemplateQuodDefMDRRule.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createQuodDefMDRRule1 = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createQuodDefMDRRule1',
                request_serializer=quod__simulator__pb2.TemplateQuodDefMDRRule.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createQuodRFQRule = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createQuodRFQRule',
                request_serializer=quod__simulator__pb2.TemplateQuodRFQRule.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createQuodRFQTRADERule = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createQuodRFQTRADERule',
                request_serializer=quod__simulator__pb2.TemplateQuodRFQTRADERule.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.createQuodPendingNewRule = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/createQuodPendingNewRule',
                request_serializer=quod__simulator__pb2.TemplatePendingNewRule.SerializeToString,
                response_deserializer=simulator__pb2.RuleID.FromString,
                )
        self.getMDRefIDForConnection = channel.unary_unary(
                '/th2.simulator.template.TemplateSimulatorService/getMDRefIDForConnection',
                request_serializer=quod__simulator__pb2.RequestMDRefID.SerializeToString,
                response_deserializer=quod__simulator__pb2.ResponseMDRefID.FromString,
                )


class TemplateSimulatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createRule_FIX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createKotlinRule_FIX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createQuodNOSRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createQuodOCRRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createQuodOCRRRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createQuodSingleExecRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createQuodMDRRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createQuodDefMDRRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createQuodDefMDRRule1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createQuodRFQRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createQuodRFQTRADERule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createQuodPendingNewRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMDRefIDForConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemplateSimulatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createRule_FIX': grpc.unary_unary_rpc_method_handler(
                    servicer.createRule_FIX,
                    request_deserializer=quod__simulator__pb2.TemplateFixCreate.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createKotlinRule_FIX': grpc.unary_unary_rpc_method_handler(
                    servicer.createKotlinRule_FIX,
                    request_deserializer=quod__simulator__pb2.TemplateFixCreate.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createQuodNOSRule': grpc.unary_unary_rpc_method_handler(
                    servicer.createQuodNOSRule,
                    request_deserializer=quod__simulator__pb2.TemplateQuodNOSRule.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createQuodOCRRule': grpc.unary_unary_rpc_method_handler(
                    servicer.createQuodOCRRule,
                    request_deserializer=quod__simulator__pb2.TemplateQuodOCRRule.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createQuodOCRRRule': grpc.unary_unary_rpc_method_handler(
                    servicer.createQuodOCRRRule,
                    request_deserializer=quod__simulator__pb2.TemplateQuodOCRRRule.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createQuodSingleExecRule': grpc.unary_unary_rpc_method_handler(
                    servicer.createQuodSingleExecRule,
                    request_deserializer=quod__simulator__pb2.TemplateQuodSingleExecRule.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createQuodMDRRule': grpc.unary_unary_rpc_method_handler(
                    servicer.createQuodMDRRule,
                    request_deserializer=quod__simulator__pb2.TemplateQuodMDRRule.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createQuodDefMDRRule': grpc.unary_unary_rpc_method_handler(
                    servicer.createQuodDefMDRRule,
                    request_deserializer=quod__simulator__pb2.TemplateQuodDefMDRRule.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createQuodDefMDRRule1': grpc.unary_unary_rpc_method_handler(
                    servicer.createQuodDefMDRRule1,
                    request_deserializer=quod__simulator__pb2.TemplateQuodDefMDRRule.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createQuodRFQRule': grpc.unary_unary_rpc_method_handler(
                    servicer.createQuodRFQRule,
                    request_deserializer=quod__simulator__pb2.TemplateQuodRFQRule.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createQuodRFQTRADERule': grpc.unary_unary_rpc_method_handler(
                    servicer.createQuodRFQTRADERule,
                    request_deserializer=quod__simulator__pb2.TemplateQuodRFQTRADERule.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'createQuodPendingNewRule': grpc.unary_unary_rpc_method_handler(
                    servicer.createQuodPendingNewRule,
                    request_deserializer=quod__simulator__pb2.TemplatePendingNewRule.FromString,
                    response_serializer=simulator__pb2.RuleID.SerializeToString,
            ),
            'getMDRefIDForConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.getMDRefIDForConnection,
                    request_deserializer=quod__simulator__pb2.RequestMDRefID.FromString,
                    response_serializer=quod__simulator__pb2.ResponseMDRefID.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'th2.simulator.template.TemplateSimulatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TemplateSimulatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createRule_FIX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createRule_FIX',
            quod__simulator__pb2.TemplateFixCreate.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createKotlinRule_FIX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createKotlinRule_FIX',
            quod__simulator__pb2.TemplateFixCreate.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createQuodNOSRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createQuodNOSRule',
            quod__simulator__pb2.TemplateQuodNOSRule.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createQuodOCRRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createQuodOCRRule',
            quod__simulator__pb2.TemplateQuodOCRRule.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createQuodOCRRRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createQuodOCRRRule',
            quod__simulator__pb2.TemplateQuodOCRRRule.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createQuodSingleExecRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createQuodSingleExecRule',
            quod__simulator__pb2.TemplateQuodSingleExecRule.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createQuodMDRRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createQuodMDRRule',
            quod__simulator__pb2.TemplateQuodMDRRule.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createQuodDefMDRRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createQuodDefMDRRule',
            quod__simulator__pb2.TemplateQuodDefMDRRule.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createQuodDefMDRRule1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createQuodDefMDRRule1',
            quod__simulator__pb2.TemplateQuodDefMDRRule.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createQuodRFQRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createQuodRFQRule',
            quod__simulator__pb2.TemplateQuodRFQRule.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createQuodRFQTRADERule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createQuodRFQTRADERule',
            quod__simulator__pb2.TemplateQuodRFQTRADERule.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createQuodPendingNewRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/createQuodPendingNewRule',
            quod__simulator__pb2.TemplatePendingNewRule.SerializeToString,
            simulator__pb2.RuleID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMDRefIDForConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.simulator.template.TemplateSimulatorService/getMDRefIDForConnection',
            quod__simulator__pb2.RequestMDRefID.SerializeToString,
            quod__simulator__pb2.ResponseMDRefID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
