# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import simulator_pb2 as simulator__pb2


class ServiceSimulatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.removeRule = channel.unary_unary(
        '/th2.ServiceSimulator/removeRule',
        request_serializer=simulator__pb2.RuleID.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.getRulesInfo = channel.unary_unary(
        '/th2.ServiceSimulator/getRulesInfo',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=simulator__pb2.RulesInfo.FromString,
        )


class ServiceSimulatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def removeRule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getRulesInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServiceSimulatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'removeRule': grpc.unary_unary_rpc_method_handler(
          servicer.removeRule,
          request_deserializer=simulator__pb2.RuleID.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'getRulesInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getRulesInfo,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=simulator__pb2.RulesInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'th2.ServiceSimulator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
