# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_modules import verifier_pb2 as verifier__pb2


class VerifierStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.createCheckpoint = channel.unary_unary(
        '/th2.Verifier/createCheckpoint',
        request_serializer=verifier__pb2.CheckpointRequest.SerializeToString,
        response_deserializer=verifier__pb2.CheckpointResponse.FromString,
        )
    self.submitCheckRule = channel.unary_unary(
        '/th2.Verifier/submitCheckRule',
        request_serializer=verifier__pb2.CheckRuleRequest.SerializeToString,
        response_deserializer=verifier__pb2.CheckRuleResponse.FromString,
        )
    self.submitCheckSequenceRule = channel.unary_unary(
        '/th2.Verifier/submitCheckSequenceRule',
        request_serializer=verifier__pb2.CheckSequenceRuleRequest.SerializeToString,
        response_deserializer=verifier__pb2.CheckSequenceRuleResponse.FromString,
        )


class VerifierServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def createCheckpoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def submitCheckRule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def submitCheckSequenceRule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VerifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'createCheckpoint': grpc.unary_unary_rpc_method_handler(
          servicer.createCheckpoint,
          request_deserializer=verifier__pb2.CheckpointRequest.FromString,
          response_serializer=verifier__pb2.CheckpointResponse.SerializeToString,
      ),
      'submitCheckRule': grpc.unary_unary_rpc_method_handler(
          servicer.submitCheckRule,
          request_deserializer=verifier__pb2.CheckRuleRequest.FromString,
          response_serializer=verifier__pb2.CheckRuleResponse.SerializeToString,
      ),
      'submitCheckSequenceRule': grpc.unary_unary_rpc_method_handler(
          servicer.submitCheckSequenceRule,
          request_deserializer=verifier__pb2.CheckSequenceRuleRequest.FromString,
          response_serializer=verifier__pb2.CheckSequenceRuleResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'th2.Verifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
